In [2]:
import pandas as pd
import numpy as np

In [3]:
ratings = pd.read_csv('data/datasets/rating/remaining_detail.csv', sep=',', encoding='latin-1')
ratings.head()

,user index,movie index,rating,content,date,user id,movie id,interaction count
0,22678,0,8.0,Murder is being done at a medieval monastery a...,24 February 2007,ur2483625,tt0091605,1311
1,22678,12,8.0,After a hiatus of over a decade Jack Lemmon an...,21 October 2012,ur2483625,tt0107050,1311
2,22678,20,7.0,Let me say from the outset I'm not a particula...,7 February 2007,ur2483625,tt0100260,1311
3,22678,26,3.0,Zac Efron's relentless drive to get away from ...,3 July 2014,ur2483625,tt2004420,1311
4,22678,29,7.0,"Towards the end of Lawman, Burt Lancaster says...",19 December 2005,ur2483625,tt0067333,1311

In [4]:
ratings

,user index,movie index,rating,content,date,user id,movie id,interaction count
0,22678,0,8.0,Murder is being done at a medieval monastery a...,24 February 2007,ur2483625,tt0091605,1311
1,22678,12,8.0,After a hiatus of over a decade Jack Lemmon an...,21 October 2012,ur2483625,tt0107050,1311
2,22678,20,7.0,Let me say from the outset I'm not a particula...,7 February 2007,ur2483625,tt0100260,1311
3,22678,26,3.0,Zac Efron's relentless drive to get away from ...,3 July 2014,ur2483625,tt2004420,1311
4,22678,29,7.0,"Towards the end of Lawman, Burt Lancaster says...",19 December 2005,ur2483625,tt0067333,1311
...,...,...,...,...,...,...,...,...
127939,21697,8303,10.0,It's been a while since I've seen The Brave Li...,16 September 2008,ur2747461,tt0092695,14
127940,21697,8387,8.0,Let's keep this little comment of mine simple ...,12 November 2009,ur2747461,tt0095473,14
127941,21697,9160,10.0,"Ninja Scroll, Heavy Metal, Iron Giant, Fritz t...",1 June 2008,ur2747461,tt0084509,14
127942,21697,9671,1.0,Wrong! More like this is gonna suck sh!t! I wa...,29 November 2007,ur2747461,tt0811073,14
127943,21697,9860,9.0,Don't you hate putting off games? You know it'...,1 April 2008,ur2747461,tt0888006,14

In [5]:
comment_and__rating_data = ratings[['content', 'rating']]

In [6]:
comment_and__rating_data

                                                  content  rating
0       Murder is being done at a medieval monastery a...     8.0
1       After a hiatus of over a decade Jack Lemmon an...     8.0
2       Let me say from the outset I'm not a particula...     7.0
3       Zac Efron's relentless drive to get away from ...     3.0
4       Towards the end of Lawman, Burt Lancaster says...     7.0
...                                                   ...     ...
127939  It's been a while since I've seen The Brave Li...    10.0
127940  Let's keep this little comment of mine simple ...     8.0
127941  Ninja Scroll, Heavy Metal, Iron Giant, Fritz t...    10.0
127942  Wrong! More like this is gonna suck sh!t! I wa...     1.0
127943  Don't you hate putting off games? You know it'...     9.0

[127944 rows x 2 columns]

In [8]:
comment_and__rating_data = comment_and__rating_data.dropna(subset=['content', 'rating'])

In [9]:
comment_and__rating_data = comment_and__rating_data.drop_duplicates(keep='first')
comment_and__rating_data

                                                  content  rating
0       Murder is being done at a medieval monastery a...     8.0
1       After a hiatus of over a decade Jack Lemmon an...     8.0
2       Let me say from the outset I'm not a particula...     7.0
3       Zac Efron's relentless drive to get away from ...     3.0
4       Towards the end of Lawman, Burt Lancaster says...     7.0
...                                                   ...     ...
127939  It's been a while since I've seen The Brave Li...    10.0
127940  Let's keep this little comment of mine simple ...     8.0
127941  Ninja Scroll, Heavy Metal, Iron Giant, Fritz t...    10.0
127942  Wrong! More like this is gonna suck sh!t! I wa...     1.0
127943  Don't you hate putting off games? You know it'...     9.0

[127880 rows x 2 columns]

In [22]:
import os
os.makedirs('data/datasets/comment_and_rating/', exist_ok = True)
output = os.path.join('data/datasets/comment_and_rating/', 'details.csv')

In [23]:
print(output)
comment_and__rating_data.to_csv(output, sep=',', encoding='latin-1', index=False)

data/datasets/comment_and_rating/details.csv