In [21]:
import pandas as pd
import numpy as np

In [22]:
movie_details = pd.read_csv('data/datasets/movie/details.csv', sep=',', encoding='latin-1')
movie_details.head()

,movie id,title,series,release year,certification,duration,average rating,rating total,genre list,content,countries of origin,official sites,languages,production companies,budget
0,tt0102813,Rover Dangerfield,NaN,1991,G,1h 14m,6.0,3K,Animation|Comedy|Family,A Vegas show dog gets ditched in the sticks an...,United States,NaN,English,NaN,NaN
1,tt1086761,Keeping Up with the Kardashians,TV Series,2006â2021,TV-14,44m,2.8,29K,Drama|Family|Reality-TV,A peek inside the exploits and privileged priv...,United States,Official sites|Official Facebook|Official Inst...,English|Spanish,NaN,NaN
2,tt0075686,Annie Hall,NaN,1977,PG,1h 33m,8.0,259K,Comedy|Romance,"Alvy Singer, a divorced Jewish comedian, refle...",United States,NaN,English|German,NaN,"$38,287,178"
3,tt1402488,Happy Feet Two,NaN,2011,PG,1h 40m,5.9,44K,Animation|Adventure|Comedy,"Mumble's son, Erik, is struggling to realize h...",Australia|United States|Antarctica|New Zealand,Official site,English,NaN,"$159,197,038"
4,tt15523186,Warning,NaN,2021,NaN,NaN,9.6,310,Action,"Set in India, Action Movie Warning is about th...",India,NaN,Punjabi,NaN,NaN

In [23]:
movie_details

,movie id,title,series,release year,certification,duration,average rating,rating total,genre list,content,countries of origin,official sites,languages,production companies,budget
0,tt0102813,Rover Dangerfield,NaN,1991,G,1h 14m,6.0,3K,Animation|Comedy|Family,A Vegas show dog gets ditched in the sticks an...,United States,NaN,English,NaN,NaN
1,tt1086761,Keeping Up with the Kardashians,TV Series,2006â2021,TV-14,44m,2.8,29K,Drama|Family|Reality-TV,A peek inside the exploits and privileged priv...,United States,Official sites|Official Facebook|Official Inst...,English|Spanish,NaN,NaN
2,tt0075686,Annie Hall,NaN,1977,PG,1h 33m,8.0,259K,Comedy|Romance,"Alvy Singer, a divorced Jewish comedian, refle...",United States,NaN,English|German,NaN,"$38,287,178"
3,tt1402488,Happy Feet Two,NaN,2011,PG,1h 40m,5.9,44K,Animation|Adventure|Comedy,"Mumble's son, Erik, is struggling to realize h...",Australia|United States|Antarctica|New Zealand,Official site,English,NaN,"$159,197,038"
4,tt15523186,Warning,NaN,2021,NaN,NaN,9.6,310,Action,"Set in India, Action Movie Warning is about th...",India,NaN,Punjabi,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9708,tt2968804,Drive Hard,NaN,2014,Not Rated,1h 32m,4.4,4.5K,Action|Comedy|Crime,A former race car driver is abducted by a myst...,Canada,Official site (Japan),English,NaN,"$267,030"
9709,tt0387199,Entourage,TV Series,2004â2011,TV-MA,28m,8.4,164K,Comedy|Drama,Film star Vince Chase navigates the vapid terr...,United States,NaN,English,NaN,NaN
9710,tt1605783,Midnight in Paris,NaN,2011,PG-13,1h 34m,7.7,406K,Comedy|Fantasy|Romance,While on a trip to Paris with his fiancÃ©e's f...,Spain|United States|France,Official sites|Official Facebook|Official Face...,English|French|Spanish|German,NaN,"$151,728,412"
9711,tt1253863,300: Rise of an Empire,NaN,2014,R,1h 42m,6.2,290K,Action|Drama,Greek general Themistokles of Athens leads the...,United States,Official Facebook|Official site (United States),English,NaN,"$337,580,051"
9712,tt8362852,Swamp Thing,TV Series,2019,TV-MA,1h,7.5,23K,Action|Adventure|Drama,"Abby Arcane returns home to Marais, Louisiana ...",United States,Official Facebook|Official site,English,NaN,NaN

In [24]:
movie_details = movie_details.drop_duplicates(keep='first')

In [25]:
movie_details

,movie id,title,series,release year,certification,duration,average rating,rating total,genre list,content,countries of origin,official sites,languages,production companies,budget
0,tt0102813,Rover Dangerfield,NaN,1991,G,1h 14m,6.0,3K,Animation|Comedy|Family,A Vegas show dog gets ditched in the sticks an...,United States,NaN,English,NaN,NaN
1,tt1086761,Keeping Up with the Kardashians,TV Series,2006â2021,TV-14,44m,2.8,29K,Drama|Family|Reality-TV,A peek inside the exploits and privileged priv...,United States,Official sites|Official Facebook|Official Inst...,English|Spanish,NaN,NaN
2,tt0075686,Annie Hall,NaN,1977,PG,1h 33m,8.0,259K,Comedy|Romance,"Alvy Singer, a divorced Jewish comedian, refle...",United States,NaN,English|German,NaN,"$38,287,178"
3,tt1402488,Happy Feet Two,NaN,2011,PG,1h 40m,5.9,44K,Animation|Adventure|Comedy,"Mumble's son, Erik, is struggling to realize h...",Australia|United States|Antarctica|New Zealand,Official site,English,NaN,"$159,197,038"
4,tt15523186,Warning,NaN,2021,NaN,NaN,9.6,310,Action,"Set in India, Action Movie Warning is about th...",India,NaN,Punjabi,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9639,tt13623580,Reservation Dogs,TV Series,2021â,TV-MA,30m,8.1,7.7K,Comedy|Crime,Comedy series about four Native American teena...,United States,NaN,English,NaN,NaN
9652,tt5442430,Life,NaN,2017,R,1h 44m,6.6,220K,Horror|Sci-Fi|Thriller,A team of scientists aboard the International ...,United Kingdom|United States,Official Site|Official Site (France),English|Japanese|Vietnamese,NaN,"$100,541,806"
9653,tt11563364,Repeat,NaN,2021,NaN,NaN,4.5,218,Drama|Mystery|Sci-Fi,A zealous cognitive psychologist dedicates his...,United Kingdom,film production website,English,NaN,NaN
9673,tt9214684,Home Economics,TV Series,2021â,TV-PG,30m,6.5,2.4K,Comedy,Three grown-up siblings find themselves living...,United States,NaN,English,NaN,NaN
9688,tt1242447,Nativity!,NaN,2009,PG,1h 45m,6.5,9.4K,Comedy|Family,An uptight but secretly heartbroken primary sc...,United Kingdom,NaN,English,NaN,"$8,496,009"

In [26]:
movie_details['production companies']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
9639   NaN
9652   NaN
9653   NaN
9673   NaN
9688   NaN
Name: production companies, Length: 8791, dtype: float64

In [27]:
movie_details = movie_details.drop(['production companies'], axis=1)
movie_details

,movie id,title,series,release year,certification,duration,average rating,rating total,genre list,content,countries of origin,official sites,languages,budget
0,tt0102813,Rover Dangerfield,NaN,1991,G,1h 14m,6.0,3K,Animation|Comedy|Family,A Vegas show dog gets ditched in the sticks an...,United States,NaN,English,NaN
1,tt1086761,Keeping Up with the Kardashians,TV Series,2006â2021,TV-14,44m,2.8,29K,Drama|Family|Reality-TV,A peek inside the exploits and privileged priv...,United States,Official sites|Official Facebook|Official Inst...,English|Spanish,NaN
2,tt0075686,Annie Hall,NaN,1977,PG,1h 33m,8.0,259K,Comedy|Romance,"Alvy Singer, a divorced Jewish comedian, refle...",United States,NaN,English|German,"$38,287,178"
3,tt1402488,Happy Feet Two,NaN,2011,PG,1h 40m,5.9,44K,Animation|Adventure|Comedy,"Mumble's son, Erik, is struggling to realize h...",Australia|United States|Antarctica|New Zealand,Official site,English,"$159,197,038"
4,tt15523186,Warning,NaN,2021,NaN,NaN,9.6,310,Action,"Set in India, Action Movie Warning is about th...",India,NaN,Punjabi,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9639,tt13623580,Reservation Dogs,TV Series,2021â,TV-MA,30m,8.1,7.7K,Comedy|Crime,Comedy series about four Native American teena...,United States,NaN,English,NaN
9652,tt5442430,Life,NaN,2017,R,1h 44m,6.6,220K,Horror|Sci-Fi|Thriller,A team of scientists aboard the International ...,United Kingdom|United States,Official Site|Official Site (France),English|Japanese|Vietnamese,"$100,541,806"
9653,tt11563364,Repeat,NaN,2021,NaN,NaN,4.5,218,Drama|Mystery|Sci-Fi,A zealous cognitive psychologist dedicates his...,United Kingdom,film production website,English,NaN
9673,tt9214684,Home Economics,TV Series,2021â,TV-PG,30m,6.5,2.4K,Comedy,Three grown-up siblings find themselves living...,United States,NaN,English,NaN
9688,tt1242447,Nativity!,NaN,2009,PG,1h 45m,6.5,9.4K,Comedy|Family,An uptight but secretly heartbroken primary sc...,United Kingdom,NaN,English,"$8,496,009"

In [28]:
movie_details['series'] = movie_details['series'].fillna('Not series')

In [29]:
movie_details

,movie id,title,series,release year,certification,duration,average rating,rating total,genre list,content,countries of origin,official sites,languages,budget
0,tt0102813,Rover Dangerfield,Not series,1991,G,1h 14m,6.0,3K,Animation|Comedy|Family,A Vegas show dog gets ditched in the sticks an...,United States,NaN,English,NaN
1,tt1086761,Keeping Up with the Kardashians,TV Series,2006â2021,TV-14,44m,2.8,29K,Drama|Family|Reality-TV,A peek inside the exploits and privileged priv...,United States,Official sites|Official Facebook|Official Inst...,English|Spanish,NaN
2,tt0075686,Annie Hall,Not series,1977,PG,1h 33m,8.0,259K,Comedy|Romance,"Alvy Singer, a divorced Jewish comedian, refle...",United States,NaN,English|German,"$38,287,178"
3,tt1402488,Happy Feet Two,Not series,2011,PG,1h 40m,5.9,44K,Animation|Adventure|Comedy,"Mumble's son, Erik, is struggling to realize h...",Australia|United States|Antarctica|New Zealand,Official site,English,"$159,197,038"
4,tt15523186,Warning,Not series,2021,NaN,NaN,9.6,310,Action,"Set in India, Action Movie Warning is about th...",India,NaN,Punjabi,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9639,tt13623580,Reservation Dogs,TV Series,2021â,TV-MA,30m,8.1,7.7K,Comedy|Crime,Comedy series about four Native American teena...,United States,NaN,English,NaN
9652,tt5442430,Life,Not series,2017,R,1h 44m,6.6,220K,Horror|Sci-Fi|Thriller,A team of scientists aboard the International ...,United Kingdom|United States,Official Site|Official Site (France),English|Japanese|Vietnamese,"$100,541,806"
9653,tt11563364,Repeat,Not series,2021,NaN,NaN,4.5,218,Drama|Mystery|Sci-Fi,A zealous cognitive psychologist dedicates his...,United Kingdom,film production website,English,NaN
9673,tt9214684,Home Economics,TV Series,2021â,TV-PG,30m,6.5,2.4K,Comedy,Three grown-up siblings find themselves living...,United States,NaN,English,NaN
9688,tt1242447,Nativity!,Not series,2009,PG,1h 45m,6.5,9.4K,Comedy|Family,An uptight but secretly heartbroken primary sc...,United Kingdom,NaN,English,"$8,496,009"

In [30]:
movie_details['release year'] = movie_details['release year'].fillna('undefined')
movie_details

,movie id,title,series,release year,certification,duration,average rating,rating total,genre list,content,countries of origin,official sites,languages,budget
0,tt0102813,Rover Dangerfield,Not series,1991,G,1h 14m,6.0,3K,Animation|Comedy|Family,A Vegas show dog gets ditched in the sticks an...,United States,NaN,English,NaN
1,tt1086761,Keeping Up with the Kardashians,TV Series,2006â2021,TV-14,44m,2.8,29K,Drama|Family|Reality-TV,A peek inside the exploits and privileged priv...,United States,Official sites|Official Facebook|Official Inst...,English|Spanish,NaN
2,tt0075686,Annie Hall,Not series,1977,PG,1h 33m,8.0,259K,Comedy|Romance,"Alvy Singer, a divorced Jewish comedian, refle...",United States,NaN,English|German,"$38,287,178"
3,tt1402488,Happy Feet Two,Not series,2011,PG,1h 40m,5.9,44K,Animation|Adventure|Comedy,"Mumble's son, Erik, is struggling to realize h...",Australia|United States|Antarctica|New Zealand,Official site,English,"$159,197,038"
4,tt15523186,Warning,Not series,2021,NaN,NaN,9.6,310,Action,"Set in India, Action Movie Warning is about th...",India,NaN,Punjabi,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9639,tt13623580,Reservation Dogs,TV Series,2021â,TV-MA,30m,8.1,7.7K,Comedy|Crime,Comedy series about four Native American teena...,United States,NaN,English,NaN
9652,tt5442430,Life,Not series,2017,R,1h 44m,6.6,220K,Horror|Sci-Fi|Thriller,A team of scientists aboard the International ...,United Kingdom|United States,Official Site|Official Site (France),English|Japanese|Vietnamese,"$100,541,806"
9653,tt11563364,Repeat,Not series,2021,NaN,NaN,4.5,218,Drama|Mystery|Sci-Fi,A zealous cognitive psychologist dedicates his...,United Kingdom,film production website,English,NaN
9673,tt9214684,Home Economics,TV Series,2021â,TV-PG,30m,6.5,2.4K,Comedy,Three grown-up siblings find themselves living...,United States,NaN,English,NaN
9688,tt1242447,Nativity!,Not series,2009,PG,1h 45m,6.5,9.4K,Comedy|Family,An uptight but secretly heartbroken primary sc...,United Kingdom,NaN,English,"$8,496,009"

In [31]:
movie_details['official sites'] = movie_details['official sites'].fillna('undefined')
movie_details

,movie id,title,series,release year,certification,duration,average rating,rating total,genre list,content,countries of origin,official sites,languages,budget
0,tt0102813,Rover Dangerfield,Not series,1991,G,1h 14m,6.0,3K,Animation|Comedy|Family,A Vegas show dog gets ditched in the sticks an...,United States,undefined,English,NaN
1,tt1086761,Keeping Up with the Kardashians,TV Series,2006â2021,TV-14,44m,2.8,29K,Drama|Family|Reality-TV,A peek inside the exploits and privileged priv...,United States,Official sites|Official Facebook|Official Inst...,English|Spanish,NaN
2,tt0075686,Annie Hall,Not series,1977,PG,1h 33m,8.0,259K,Comedy|Romance,"Alvy Singer, a divorced Jewish comedian, refle...",United States,undefined,English|German,"$38,287,178"
3,tt1402488,Happy Feet Two,Not series,2011,PG,1h 40m,5.9,44K,Animation|Adventure|Comedy,"Mumble's son, Erik, is struggling to realize h...",Australia|United States|Antarctica|New Zealand,Official site,English,"$159,197,038"
4,tt15523186,Warning,Not series,2021,NaN,NaN,9.6,310,Action,"Set in India, Action Movie Warning is about th...",India,undefined,Punjabi,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9639,tt13623580,Reservation Dogs,TV Series,2021â,TV-MA,30m,8.1,7.7K,Comedy|Crime,Comedy series about four Native American teena...,United States,undefined,English,NaN
9652,tt5442430,Life,Not series,2017,R,1h 44m,6.6,220K,Horror|Sci-Fi|Thriller,A team of scientists aboard the International ...,United Kingdom|United States,Official Site|Official Site (France),English|Japanese|Vietnamese,"$100,541,806"
9653,tt11563364,Repeat,Not series,2021,NaN,NaN,4.5,218,Drama|Mystery|Sci-Fi,A zealous cognitive psychologist dedicates his...,United Kingdom,film production website,English,NaN
9673,tt9214684,Home Economics,TV Series,2021â,TV-PG,30m,6.5,2.4K,Comedy,Three grown-up siblings find themselves living...,United States,undefined,English,NaN
9688,tt1242447,Nativity!,Not series,2009,PG,1h 45m,6.5,9.4K,Comedy|Family,An uptight but secretly heartbroken primary sc...,United Kingdom,undefined,English,"$8,496,009"

In [32]:
movie_details['certification'] = movie_details['certification'].fillna('others') 
movie_details

,movie id,title,series,release year,certification,duration,average rating,rating total,genre list,content,countries of origin,official sites,languages,budget
0,tt0102813,Rover Dangerfield,Not series,1991,G,1h 14m,6.0,3K,Animation|Comedy|Family,A Vegas show dog gets ditched in the sticks an...,United States,undefined,English,NaN
1,tt1086761,Keeping Up with the Kardashians,TV Series,2006â2021,TV-14,44m,2.8,29K,Drama|Family|Reality-TV,A peek inside the exploits and privileged priv...,United States,Official sites|Official Facebook|Official Inst...,English|Spanish,NaN
2,tt0075686,Annie Hall,Not series,1977,PG,1h 33m,8.0,259K,Comedy|Romance,"Alvy Singer, a divorced Jewish comedian, refle...",United States,undefined,English|German,"$38,287,178"
3,tt1402488,Happy Feet Two,Not series,2011,PG,1h 40m,5.9,44K,Animation|Adventure|Comedy,"Mumble's son, Erik, is struggling to realize h...",Australia|United States|Antarctica|New Zealand,Official site,English,"$159,197,038"
4,tt15523186,Warning,Not series,2021,others,NaN,9.6,310,Action,"Set in India, Action Movie Warning is about th...",India,undefined,Punjabi,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9639,tt13623580,Reservation Dogs,TV Series,2021â,TV-MA,30m,8.1,7.7K,Comedy|Crime,Comedy series about four Native American teena...,United States,undefined,English,NaN
9652,tt5442430,Life,Not series,2017,R,1h 44m,6.6,220K,Horror|Sci-Fi|Thriller,A team of scientists aboard the International ...,United Kingdom|United States,Official Site|Official Site (France),English|Japanese|Vietnamese,"$100,541,806"
9653,tt11563364,Repeat,Not series,2021,others,NaN,4.5,218,Drama|Mystery|Sci-Fi,A zealous cognitive psychologist dedicates his...,United Kingdom,film production website,English,NaN
9673,tt9214684,Home Economics,TV Series,2021â,TV-PG,30m,6.5,2.4K,Comedy,Three grown-up siblings find themselves living...,United States,undefined,English,NaN
9688,tt1242447,Nativity!,Not series,2009,PG,1h 45m,6.5,9.4K,Comedy|Family,An uptight but secretly heartbroken primary sc...,United Kingdom,undefined,English,"$8,496,009"

In [33]:
movie_details['duration'] = movie_details['duration'].fillna('undefined')
movie_details

,movie id,title,series,release year,certification,duration,average rating,rating total,genre list,content,countries of origin,official sites,languages,budget
0,tt0102813,Rover Dangerfield,Not series,1991,G,1h 14m,6.0,3K,Animation|Comedy|Family,A Vegas show dog gets ditched in the sticks an...,United States,undefined,English,NaN
1,tt1086761,Keeping Up with the Kardashians,TV Series,2006â2021,TV-14,44m,2.8,29K,Drama|Family|Reality-TV,A peek inside the exploits and privileged priv...,United States,Official sites|Official Facebook|Official Inst...,English|Spanish,NaN
2,tt0075686,Annie Hall,Not series,1977,PG,1h 33m,8.0,259K,Comedy|Romance,"Alvy Singer, a divorced Jewish comedian, refle...",United States,undefined,English|German,"$38,287,178"
3,tt1402488,Happy Feet Two,Not series,2011,PG,1h 40m,5.9,44K,Animation|Adventure|Comedy,"Mumble's son, Erik, is struggling to realize h...",Australia|United States|Antarctica|New Zealand,Official site,English,"$159,197,038"
4,tt15523186,Warning,Not series,2021,others,undefined,9.6,310,Action,"Set in India, Action Movie Warning is about th...",India,undefined,Punjabi,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9639,tt13623580,Reservation Dogs,TV Series,2021â,TV-MA,30m,8.1,7.7K,Comedy|Crime,Comedy series about four Native American teena...,United States,undefined,English,NaN
9652,tt5442430,Life,Not series,2017,R,1h 44m,6.6,220K,Horror|Sci-Fi|Thriller,A team of scientists aboard the International ...,United Kingdom|United States,Official Site|Official Site (France),English|Japanese|Vietnamese,"$100,541,806"
9653,tt11563364,Repeat,Not series,2021,others,undefined,4.5,218,Drama|Mystery|Sci-Fi,A zealous cognitive psychologist dedicates his...,United Kingdom,film production website,English,NaN
9673,tt9214684,Home Economics,TV Series,2021â,TV-PG,30m,6.5,2.4K,Comedy,Three grown-up siblings find themselves living...,United States,undefined,English,NaN
9688,tt1242447,Nativity!,Not series,2009,PG,1h 45m,6.5,9.4K,Comedy|Family,An uptight but secretly heartbroken primary sc...,United Kingdom,undefined,English,"$8,496,009"

In [34]:
movie_details['budget'] = movie_details['budget'].fillna('undefined')
movie_details

,movie id,title,series,release year,certification,duration,average rating,rating total,genre list,content,countries of origin,official sites,languages,budget
0,tt0102813,Rover Dangerfield,Not series,1991,G,1h 14m,6.0,3K,Animation|Comedy|Family,A Vegas show dog gets ditched in the sticks an...,United States,undefined,English,undefined
1,tt1086761,Keeping Up with the Kardashians,TV Series,2006â2021,TV-14,44m,2.8,29K,Drama|Family|Reality-TV,A peek inside the exploits and privileged priv...,United States,Official sites|Official Facebook|Official Inst...,English|Spanish,undefined
2,tt0075686,Annie Hall,Not series,1977,PG,1h 33m,8.0,259K,Comedy|Romance,"Alvy Singer, a divorced Jewish comedian, refle...",United States,undefined,English|German,"$38,287,178"
3,tt1402488,Happy Feet Two,Not series,2011,PG,1h 40m,5.9,44K,Animation|Adventure|Comedy,"Mumble's son, Erik, is struggling to realize h...",Australia|United States|Antarctica|New Zealand,Official site,English,"$159,197,038"
4,tt15523186,Warning,Not series,2021,others,undefined,9.6,310,Action,"Set in India, Action Movie Warning is about th...",India,undefined,Punjabi,undefined
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9639,tt13623580,Reservation Dogs,TV Series,2021â,TV-MA,30m,8.1,7.7K,Comedy|Crime,Comedy series about four Native American teena...,United States,undefined,English,undefined
9652,tt5442430,Life,Not series,2017,R,1h 44m,6.6,220K,Horror|Sci-Fi|Thriller,A team of scientists aboard the International ...,United Kingdom|United States,Official Site|Official Site (France),English|Japanese|Vietnamese,"$100,541,806"
9653,tt11563364,Repeat,Not series,2021,others,undefined,4.5,218,Drama|Mystery|Sci-Fi,A zealous cognitive psychologist dedicates his...,United Kingdom,film production website,English,undefined
9673,tt9214684,Home Economics,TV Series,2021â,TV-PG,30m,6.5,2.4K,Comedy,Three grown-up siblings find themselves living...,United States,undefined,English,undefined
9688,tt1242447,Nativity!,Not series,2009,PG,1h 45m,6.5,9.4K,Comedy|Family,An uptight but secretly heartbroken primary sc...,United Kingdom,undefined,English,"$8,496,009"

In [35]:
import os

output = os.path.join('data/datasets/movie/', 'preprocessed_details.csv')
print(output)
movie_details.to_csv(output, sep=',', encoding='latin-1', index=False)

data/datasets/movie/preprocessed_details.csv

In [36]:
content_and_average_rating_data = movie_details[['content', 'average rating']]

In [37]:
content_and_average_rating_data

                                                content  average rating
0     A Vegas show dog gets ditched in the sticks an...             6.0
1     A peek inside the exploits and privileged priv...             2.8
2     Alvy Singer, a divorced Jewish comedian, refle...             8.0
3     Mumble's son, Erik, is struggling to realize h...             5.9
4     Set in India, Action Movie Warning is about th...             9.6
...                                                 ...             ...
9639  Comedy series about four Native American teena...             8.1
9652  A team of scientists aboard the International ...             6.6
9653  A zealous cognitive psychologist dedicates his...             4.5
9673  Three grown-up siblings find themselves living...             6.5
9688  An uptight but secretly heartbroken primary sc...             6.5

[8791 rows x 2 columns]

In [38]:
content_and_average_rating_data = content_and_average_rating_data.dropna(subset=['content', 'average rating'])

In [39]:
content_and_average_rating_data = content_and_average_rating_data.drop_duplicates(keep='first')
content_and_average_rating_data

                                                content  average rating
0     A Vegas show dog gets ditched in the sticks an...             6.0
1     A peek inside the exploits and privileged priv...             2.8
2     Alvy Singer, a divorced Jewish comedian, refle...             8.0
3     Mumble's son, Erik, is struggling to realize h...             5.9
4     Set in India, Action Movie Warning is about th...             9.6
...                                                 ...             ...
9512  Bud is a young man from the country who learns...             6.4
9541  The lives and work of the staff of an inner ci...             8.2
9585  The story of Barney, an awkward middle-schoole...             7.1
9653  A zealous cognitive psychologist dedicates his...             4.5
9673  Three grown-up siblings find themselves living...             6.5

[8569 rows x 2 columns]

In [40]:
import os

output = os.path.join('data/datasets/content_and_rating/', 'details.csv')
print(output)
content_and_average_rating_data.to_csv(output, sep=',', encoding='latin-1', index=False)

data/datasets/content_and_rating/details.csv