In [1]:
import pandas as pd
import numpy as np

In [2]:
ratings = pd.read_csv('./data/datasets/rating/preprocessed_detail.csv', sep=',', encoding='latin-1')

In [3]:
ratings

,user id,movie id,rating,content,date
0,ur20552756,tt0102813,3,I am a big fan of animated movies and of anima...,22 June 2011
1,ur0391152,tt0102813,2,I've always had kind of a perverse curiosity a...,22 August 2010
2,ur34049683,tt0102813,3,Everything about this movie is from the mind o...,14 March 2013
3,ur23566468,tt0102813,3,Rover Dangerfield is loosely based on the late...,20 April 2020
4,ur4195782,tt0102813,2,I started out this movie with a positive attit...,8 August 2008
...,...,...,...,...,...
162072,ur1173088,tt0131704,2,The beginning of this movie is promising. It s...,29 June 2005
162073,ur2444068,tt0131704,3,Boris (Jason Alexander) and Natasha (Rene Russ...,20 January 2007
162074,ur0543054,tt0131704,3,"Somewhere in the heart of Frostbite Falls, our...",13 July 2000
162075,ur0631986,tt0131704,3,1st watched 3/10/2001 - (Dir-Des McAnuff) Humo...,10 March 2001
162076,ur0068788,tt0131704,5,I've been wanting to see this since I first he...,2 July 2001

In [4]:
no_ratings_per_user = ratings.groupby('user id').count()['rating']

In [5]:
no_ratings_per_user

user id
ur0000011      1
ur0001220      2
ur0002746     10
ur0003136      5
ur0003696      6
              ..
ur99936512     1
ur99957464     1
ur99964320     2
ur99969779     1
ur99992944     1
Name: rating, Length: 22695, dtype: int64

In [6]:
user_ids = ratings.groupby('user id').count()['rating'].index.tolist()
user_ids = np.array(user_ids)

In [7]:
user_ids

array(['ur0000011', 'ur0001220', 'ur0002746', ..., 'ur99964320',
       'ur99969779', 'ur99992944'], dtype='<U11')

In [8]:
no_ratings_per_user = np.array(no_ratings_per_user)
user_id_idxes = np.argsort(no_ratings_per_user).tolist()

In [9]:
for i in range(len(user_id_idxes[:1415])):
    idx = user_id_idxes[len(user_id_idxes) - i - 1]
    print(user_ids[idx], no_ratings_per_user[idx])

ur2898520 5163
ur4248714 3175
ur5876717 2996
ur0482513 2827
ur20552756 2622
ur2488512 2089
ur4888011 2025
ur1234929 1907
ur0453068 1901
ur77881167 1872
ur2467618 1687
ur2707735 1677
ur13977076 1621
ur22654354 1560
ur0945066 1547
ur4569900 1442
ur2483625 1311
ur0989035 1295
ur0449021 1269
ur3270789 1253
ur4445210 1138
ur0819382 1008
ur0278527 1001
ur3670492 990
ur7813355 970
ur16161013 929
ur2020269 901
ur5291991 820
ur60028700 817
ur2860723 803
ur3914439 795
ur2079400 794
ur69172350 790
ur0342623 784
ur33374263 782
ur76062573 776
ur2542703 722
ur107065132 711
ur0463200 696
ur1532177 688
ur28159509 678
ur58525162 663
ur11228318 626
ur22668817 615
ur23359813 594
ur18044142 571
ur0806494 566
ur1416505 561
ur0968789 560
ur22484170 551
ur15311310 541
ur29385135 530
ur2093818 528
ur15896852 527
ur8239592 517
ur2171244 511
ur0937743 498
ur9938570 494
ur3079504 489
ur104603847 487
ur3146136 486
ur1355507 481
ur0011762 480
ur4532636 477
ur15977902 424
ur1293485 403
ur1896124 393
ur12844960 393
ur71305899 364
ur34836174 351
ur50489624 347
ur1406078 345
ur1111192 325
ur23577930 325
ur44112735 322
ur26820801 317
ur0317399 315
ur25837689 307
ur3223254 303
ur4409266 301
ur100229298 299
ur23483288 297
ur8503729 293
ur79950921 293
ur1994077 292
ur57691865 289
ur0391152 277
ur9927546 276
ur0033913 275
ur2567136 274
ur5424352 274
ur17825945 273
ur36357573 270
ur64798417 267
ur22171966 262
ur23566468 256
ur25790270 244
ur49392790 234
ur64264987 232
ur23581966 232
ur0453228 230
ur1048771 225
ur5788055 222
ur1219578 221
ur43949288 221
ur1399158 219
ur1617546 215
ur11423174 213
ur2582239 211
ur79683341 206
ur3967726 205
ur14520497 204
ur39517558 204
ur64160263 200
ur2955724 198
ur49848930 198
ur25775215 194
ur54314810 194
ur33907744 189
ur1697212 189
ur79460801 189
ur34845698 181
ur2444068 178
ur4405474 177
ur13538926 176
ur0783721 175
ur56005872 173
ur15148330 173
ur11523087 170
ur0437174 170
ur8462477 170
ur6201371 170
ur1406466 164
ur17559480 164
ur71506838 163
ur1888886 162
ur20327151 160
ur1173088 158
ur6141756 156
ur0715971 155
ur31328960 154
ur0972645 154
ur40547513 152
ur2248099 152
ur2095936 152
ur32764997 151
ur68519886 150
ur66601046 150
ur3793011 148
ur4067661 147
ur12596887 146
ur1162550 144
ur94289145 144
ur34307814 143
ur23589178 143
ur34226907 143
ur0345596 140
ur23018536 139
ur0650255 139
ur27175177 138
ur71501643 137
ur78277499 136
ur131783850 136
ur15298231 135
ur82872124 135
ur55640799 134
ur2082018 134
ur2263198 132
ur68881398 130
ur4944007 129
ur17816293 129
ur19752191 128
ur58792324 127
ur19892892 126
ur6387867 125
ur34435688 124
ur18970655 123
ur0375636 123
ur48560127 122
ur17901972 120
ur0386241 119
ur0547823 119
ur59627333 118
ur125168510 118
ur48675674 118
ur1773414 117
ur23138767 117
ur57590728 117
ur25217752 117
ur4593705 116
ur3836774 116
ur130195767 114
ur34049683 113
ur1683855 111
ur79190944 110
ur91315068 109
ur24085266 108
ur98906416 108
ur84596117 108
ur27582881 106
ur3071695 106
ur12048299 106
ur24931284 106
ur69864183 103
ur0663392 101
ur2745984 100
ur23055365 99
ur78948186 99
ur69745746 98
ur73668075 97
ur50296294 96
ur20309759 96
ur28260582 96
ur1616919 96
ur71516783 95
ur6325108 94
ur0865972 94
ur49400835 93
ur119082541 92
ur117926588 92
ur22761455 92
ur85371862 92
ur0102816 92
ur26578226 90
ur0331289 90
ur6251613 89
ur0872211 88
ur4234119 88
ur29107311 87
ur6587670 86
ur52600820 85
ur84924605 84
ur12682317 83
ur35635716 82
ur34187486 81
ur2929860 81
ur2403537 81
ur0101706 81
ur0892646 80
ur104021780 80
ur13211310 80
ur113506463 80
ur22487163 80
ur12332223 80
ur78018459 79
ur6918917 79
ur8131454 78
ur105954145 78
ur68345682 77
ur15795433 77
ur17646017 76
ur0351766 74
ur1257208 73
ur30163554 73
ur44588015 73
ur34967775 72
ur111092901 72
ur112380085 71
ur4915915 70
ur3109237 69
ur1355003 69
ur67902729 69
ur66111139 69
ur71356826 69
ur2626332 69
ur4103165 68
ur1980092 68
ur7826013 68
ur116970440 67
ur2843647 67
ur30872044 66
ur30077883 65
ur4465293 65
ur25057297 65
ur118439842 65
ur45707659 65
ur74113527 65
ur7850750 64
ur29500838 64
ur25552762 63
ur89333699 63
ur49074014 62
ur23188638 62
ur23887409 62
ur55157303 61
ur75340345 61
ur7743887 61
ur142375144 61
ur126619686 61
ur113268676 61
ur14295241 60
ur51094543 60
ur18723110 59
ur35944897 59
ur60227834 59
ur87068272 57
ur6305926 57
ur1931604 56
ur53053227 56
ur60965299 55
ur48282208 55
ur85976313 55
ur78375856 55
ur8271923 54
ur94560739 54
ur49392222 54
ur83178856 54
ur20231624 54
ur47204983 53
ur4145136 52
ur23183310 52
ur50463365 52
ur30091810 52
ur91222832 51
ur88270629 51
ur134783880 51
ur3225430 51
ur87786768 51
ur0070535 50
ur2154134 50
ur51181843 50
ur44482045 50
ur5348015 50
ur27361979 50
ur0850869 50
ur13371508 49
ur121340923 49
ur103498042 48
ur24907049 48
ur46915265 48
ur53388186 48
ur125007632 48
ur3501803 47
ur82784830 47
ur57284019 47
ur41285353 47
ur32544613 47
ur23831210 47
ur82146887 46
ur81499083 46
ur13630333 46
ur31098854 46
ur1964495 46
ur68133936 46
ur68532916 46
ur24365278 46
ur25226117 46
ur71272418 46
ur8201706 46
ur86595662 46
ur66711472 46
ur70346195 46
ur70609419 45
ur17087537 45
ur26030604 45
ur18338773 45
ur17732486 45
ur9516916 44
ur55513445 44
ur90278387 44
ur1588706 43
ur0509769 43
ur8062935 43
ur23318905 43
ur0874373 43
ur27343685 43
ur112657298 43
ur61206453 43
ur61891359 42
ur32235533 42
ur26163020 42
ur43363139 42
ur57285538 42
ur52569309 42
ur22956348 41
ur46919419 41
ur24207434 41
ur0812029 41
ur40032021 41
ur25312605 41
ur3580907 41
ur44661012 41
ur20961309 40
ur24054983 40
ur14630819 40
ur35502638 40
ur102601261 40
ur2366174 40
ur35725947 40
ur3280905 39
ur81031037 39
ur1369762 39
ur3741220 39
ur1090944 39
ur2590596 39
ur37533654 39
ur17571044 39
ur10115739 39
ur101705202 39
ur45288585 39
ur111426842 39
ur58619720 39
ur34738421 39
ur1159678 39
ur17924275 39
ur29002389 38
ur12161715 38
ur28071275 38
ur79796304 38
ur118284470 38
ur26083589 38
ur23240045 38
ur4834714 37
ur58781741 37
ur91490177 37
ur2484839 37
ur109685083 37
ur74931296 37
ur53576145 37
ur93064197 37
ur98571307 37
ur1803589 36
ur125953851 36
ur10774147 36
ur91189245 36
ur20060108 36
ur126911477 36
ur94671559 36
ur23858655 36
ur14095545 36
ur5177700 36
ur1634796 36
ur8977071 36
ur51294955 36
ur11358734 35
ur41485753 35
ur118665987 35
ur1530907 35
ur85220553 35
ur0442119 35
ur2609601 35
ur98786654 35
ur87850731 35
ur0631986 35
ur4195782 35
ur22652704 34
ur12527639 34
ur77092838 34
ur54906652 34
ur13288300 34
ur65737204 34
ur10357384 34
ur26579233 34
ur83822756 34
ur69892343 34
ur1132073 34
ur69153149 34
ur0879559 33
ur111005416 33
ur62660431 33
ur22864666 33
ur67325954 33
ur10067675 32
ur29755759 32
ur113370202 32
ur107340115 32
ur38492175 32
ur87748969 32
ur120321993 32
ur0361658 32
ur58195064 32
ur55939461 32
ur126266447 31
ur2904081 31
ur106279729 31
ur15711750 31
ur53732923 31
ur48961864 31
ur16336334 31
ur85162534 31
ur12740916 31
ur20402944 31
ur27077890 31
ur117097528 31
ur0562732 30
ur45390749 30
ur83607055 30
ur73109146 30
ur23402006 30
ur102732419 30
ur22206328 30
ur15651776 30
ur79431623 30
ur47100167 30
ur0855231 30
ur42414764 29
ur61702090 29
ur84682955 29
ur133290271 29
ur102184407 29
ur69878054 29
ur104763420 29
ur26639083 29
ur65205095 29
ur0491610 29
ur5466406 29
ur34410526 29
ur1148847 29
ur19998007 29
ur30753782 29
ur107152571 29
ur18437585 29
ur113529171 29
ur0583640 29
ur6025018 28
ur44306450 28
ur49080270 28
ur45461313 28
ur22996114 28
ur61568240 28
ur24593235 28
ur13887584 28
ur39634854 28
ur110143882 28
ur85564866 28
ur19278556 28
ur3056473 28
ur22826047 27
ur69858713 27
ur31117020 27
ur15588823 27
ur40016938 27
ur57213624 27
ur86505257 27
ur74108860 27
ur87984636 27
ur90265605 27
ur102222939 27
ur13035875 27
ur28095258 27
ur80775867 27
ur104081577 27
ur20597848 27
ur85483078 27
ur46685920 27
ur112035303 26
ur47246436 26
ur20748638 26
ur4669024 26
ur78573336 26
ur18423640 26
ur130506467 26
ur16126010 26
ur1370070 26
ur2709206 26
ur105856169 26
ur103624323 26
ur2293681 26
ur139168789 26
ur74935180 26
ur20096899 26
ur67430579 26
ur25263169 26
ur67306446 26
ur106007927 26
ur54692175 26
ur79317583 26
ur52993466 26
ur1602433 25
ur0538858 25
ur87984559 25
ur15375264 25
ur5946448 25
ur0090767 25
ur62249628 25
ur6739749 25
ur98727037 25
ur1064827 25
ur125934623 25
ur27018907 25
ur59110401 25
ur24755804 25
ur98824201 25
ur22003481 25
ur0225436 25
ur62460576 25
ur103468007 25
ur0730388 25
ur47382469 25
ur0350076 25
ur22186567 25
ur53814270 25
ur87946145 24
ur26266323 24
ur59144688 24
ur55597043 24
ur11335477 24
ur67478381 24
ur48427941 24
ur63251546 24
ur4294858 24
ur126952560 24
ur96002443 24
ur77838279 24
ur81864032 24
ur60195330 24
ur61194652 24
ur41031967 24
ur119939766 24
ur18946496 24
ur2419668 24
ur32568896 24
ur61706810 24
ur1696608 24
ur0792758 24
ur4580541 24
ur67595110 24
ur127155319 24
ur16773950 24
ur115227177 23
ur5115203 23
ur75875398 23
ur97978800 23
ur0165374 23
ur44717123 23
ur122397455 23
ur80691527 23
ur19392148 23
ur5232724 23
ur5625948 23
ur131101255 23
ur6927864 23
ur47190847 23
ur5526520 23
ur104563194 23
ur99782462 23
ur64990197 23
ur38215575 23
ur0826090 23
ur91998110 23
ur17471213 23
ur2950235 23
ur87042890 23
ur82016772 23
ur75193729 23
ur11215533 23
ur124770392 23
ur40512810 23
ur2166662 23
ur121054481 23
ur108282385 23
ur55322044 23
ur52251585 23
ur40516374 23
ur22982565 23
ur42927804 23
ur0111731 23
ur58232116 23
ur20336887 22
ur60545327 22
ur1966301 22
ur23304576 22
ur3072427 22
ur18431344 22
ur27637510 22
ur5268350 22
ur64604296 22
ur86230128 22
ur88708820 22
ur54023586 22
ur2706684 22
ur60068164 22
ur54867897 22
ur54176053 22
ur17389661 22
ur3886859 22
ur23281514 22
ur72164454 22
ur3588397 22
ur46647047 22
ur9227049 22
ur1192722 22
ur69980801 22
ur67945761 22
ur38614372 22
ur89370109 21
ur2904674 21
ur6981752 21
ur59376203 21
ur9987799 21
ur16750431 21
ur88373850 21
ur4512019 21
ur5392144 21
ur3610419 21
ur1581184 21
ur3608743 21
ur68045216 21
ur23365095 21
ur0637715 21
ur60027662 21
ur21404273 21
ur19511193 21
ur0064493 21
ur20250079 21
ur8046532 21
ur57765841 21
ur31261952 21
ur0178741 21
ur88923138 21
ur135212298 21
ur55225553 21
ur3513409 21
ur28911673 21
ur2021461 21
ur86674245 21
ur48779501 21
ur106735135 21
ur70682706 20
ur99479682 20
ur46356078 20
ur114205379 20
ur82002563 20
ur17731534 20
ur94986533 20
ur67651029 20
ur57088858 20
ur56957037 20
ur99809306 20
ur19484559 20
ur0204528 20
ur85901673 20
ur68176810 20
ur18449099 20
ur101559732 20
ur1062771 20
ur56526203 20
ur1609501 20
ur12144093 20
ur6643268 20
ur29565770 20
ur2721657 20
ur16558990 20
ur25694706 20
ur47630115 20
ur20962118 20
ur32680209 20
ur57189960 19
ur67801172 19
ur65932704 19
ur57198382 19
ur41552750 19
ur32512011 19
ur66427619 19
ur98088930 19
ur43666830 19
ur0495697 19
ur5108679 19
ur117202813 19
ur13566917 19
ur48308797 19
ur127985847 19
ur66979966 19
ur105506099 19
ur94005246 19
ur39696525 19
ur52856345 19
ur32545718 19
ur111412436 19
ur0543054 19
ur1677427 19
ur20506225 19
ur82462880 19
ur2613818 19
ur77131575 19
ur15104159 19
ur109374849 19
ur1517556 19
ur73908325 19
ur118728304 19
ur1985363 19
ur19023771 19
ur0394025 19
ur7048882 19
ur11901761 18
ur105082429 18
ur57396250 18
ur1100711 18
ur58133193 18
ur66106173 18
ur28237482 18
ur57396192 18
ur24390444 18
ur1596808 18
ur65256868 18
ur91940320 18
ur26154754 18
ur0222418 18
ur100698011 18
ur3582979 18
ur10501479 18
ur110145410 18
ur0312444 18
ur3329978 18
ur55056252 18
ur16749093 18
ur4258330 18
ur15462771 18
ur19897085 18
ur42434289 18
ur23853676 18
ur53475492 18
ur35343017 18
ur48432998 18
ur69620564 18
ur6663090 18
ur14678985 18
ur3332368 18
ur68159882 18
ur71629917 18
ur19868562 18
ur69946382 18
ur80922659 18
ur51507991 18
ur29496881 18
ur67334856 18
ur19368298 18
ur15112828 17
ur0955440 17
ur77085352 17
ur122781086 17
ur10384462 17
ur1113856 17
ur43600791 17
ur5175792 17
ur26835138 17
ur4006751 17
ur1977084 17
ur27125033 17
ur0137908 17
ur89572875 17
ur3578650 17
ur8929656 17
ur99519886 17
ur14702719 17
ur102431840 17
ur50241333 17
ur69239269 17
ur36422659 17
ur115774856 17
ur111831007 17
ur15445210 17
ur6177494 17
ur46717069 17
ur36590018 17
ur47246324 17
ur75650931 17
ur3783846 17
ur50107221 17
ur62452126 17
ur0347711 17
ur78310344 17
ur58898824 17
ur54330302 17
ur8167945 17
ur54011929 17
ur90845220 17
ur3966946 17
ur61124370 17
ur89493617 17
ur21881328 17
ur64376466 17
ur24181359 17
ur1935875 17
ur16567048 16
ur66690288 16
ur79118814 16
ur92315547 16
ur80693802 16
ur1046557 16
ur59844801 16
ur74022315 16
ur41730297 16
ur69427158 16
ur9488819 16
ur78542739 16
ur89269798 16
ur107273206 16
ur109023433 16
ur69481828 16
ur7383416 16
ur6302267 16
ur67826053 16
ur92127176 16
ur43219975 16
ur21110209 16
ur5153691 16
ur58672953 16
ur91525484 16
ur71100372 16
ur12680645 16
ur82396246 16
ur3666644 16
ur1893630 16
ur116641944 16
ur85802235 16
ur68612934 16
ur2216443 16
ur1738956 16
ur124402254 16
ur25126113 16
ur34443949 16
ur0489763 16
ur60946497 16
ur15060576 16
ur108851030 16
ur89584137 16
ur63469855 16
ur129636274 16
ur9414155 16
ur2496397 16
ur108426522 16
ur24357805 15
ur1444027 15
ur34790048 15
ur11701403 15
ur79273104 15
ur0327799 15
ur14236266 15
ur8625456 15
ur47816750 15
ur95950840 15
ur1332263 15
ur28643054 15
ur109188739 15
ur4101690 15
ur109505309 15
ur2306546 15
ur24171148 15
ur2862544 15
ur53582442 15
ur118562022 15
ur50306943 15
ur37568851 15
ur104062880 15
ur81872808 15
ur116666293 15
ur133004424 15
ur58341098 15
ur0097585 15
ur13863190 15
ur80388571 15
ur65673698 15
ur90750895 15
ur49417836 15
ur37365377 15
ur3530868 15
ur8766134 15
ur4555280 15
ur21618942 15
ur114026501 15
ur13269908 15
ur4980432 15
ur65491461 15
ur0689691 15
ur37569728 15
ur2722583 15
ur29589601 15
ur82980682 15
ur24673102 15
ur14477953 15
ur102935740 15
ur70587126 15
ur37647343 15
ur1004378 15
ur125176958 15
ur110936802 15
ur119716047 15
ur65374826 15
ur35669238 15
ur22008076 14
ur53096283 14
ur23129480 14
ur103297681 14
ur13401764 14
ur62933173 14
ur5755522 14
ur23501644 14
ur3619160 14
ur112666300 14
ur18913786 14
ur14080241 14
ur67641546 14
ur19048737 14
ur24230755 14
ur3443744 14
ur92678607 14
ur2747461 14
ur15140057 14
ur26149494 14
ur46761872 14
ur23062922 14
ur1601212 14
ur25497641 14
ur49839013 14
ur85229369 14
ur23922107 14
ur96545050 14
ur14156875 14
ur87676874 14
ur107515161 14
ur63857399 14
ur101633117 14
ur2375140 14
ur55815621 14
ur78403857 14
ur2790158 14
ur34857808 14
ur18058645 14
ur10491760 14
ur87184168 14
ur12653073 14
ur10734326 14
ur2415124 14
ur46485353 14
ur50646435 14
ur23388363 14
ur95437439 14
ur8232125 14
ur10279982 14
ur54076421 14
ur95459254 14
ur118977607 14
ur3972182 13
ur3835197 13
ur13880762 13
ur35638721 13
ur35088103 13
ur8112773 13
ur1590118 13
ur23426612 13
ur10797344 13
ur34290913 13
ur16318368 13
ur72321722 13
ur24340247 13
ur75224754 13
ur2735453 13
ur29218738 13
ur45967980 13
ur67039799 13
ur71384678 13
ur87242396 13
ur46714023 13
ur88522040 13
ur104886557 13
ur69383645 13
ur88574233 13
ur26226712 13
ur4034943 13
ur79825992 13
ur98033888 13
ur102956159 13
ur18073308 13
ur90253449 13
ur100147162 13
ur98002597 13
ur63878031 13
ur62963353 13
ur78811141 13
ur2042633 13
ur70977263 13
ur69496651 13
ur82337751 13
ur111600366 13
ur7588529 13
ur24292397 13
ur35205065 13
ur28344221 13
ur111479521 13
ur26591649 13
ur39765889 13
ur117424303 13
ur99149063 13
ur58149889 13
ur78300033 13
ur52678851 13
ur24062644 13
ur133291024 13
ur82400084 13
ur2300673 13
ur8202613 13
ur126737391 13
ur118161469 13
ur3533814 13
ur20621243 13
ur23466126 13
ur47173999 13
ur120600318 13
ur38833703 13
ur60189604 13
ur31543424 13
ur20767592 13
ur37116501 13
ur113058436 13
ur4627372 13
ur24880647 13
ur134654371 12
ur84479231 12
ur68129390 12
ur69609782 12
ur2951437 12
ur129739541 12
ur126800534 12
ur78124884 12
ur50644676 12
ur35662047 12
ur117454055 12
ur4780626 12
ur31646645 12
ur127588122 12
ur26504451 12
ur117788009 12
ur2264263 12
ur131821017 12
ur126541812 12
ur39615797 12
ur52270196 12
ur75217297 12
ur22910970 12
ur99741868 12
ur24865064 12
ur112589361 12
ur0068788 12
ur45504871 12
ur23991256 12
ur11590833 12
ur125165080 12
ur109186594 12
ur86341403 12
ur113853679 12
ur24612608 12
ur16650558 12
ur92732830 12
ur125357873 12
ur4308028 12
ur9230017 12
ur115616659 12
ur14612223 12
ur92254486 12
ur3947986 12
ur73504668 12
ur20375346 12
ur96316405 12
ur120696687 12
ur10230663 12
ur1878251 12
ur131685693 12
ur77466787 12
ur110325333 12
ur106024418 12
ur40211592 12
ur0176092 12
ur25362190 12
ur0394738 12
ur3902771 12
ur33234522 12
ur27129193 12
ur61197531 12
ur69270793 12
ur20343819 12
ur22509289 12
ur0035229 12
ur59437364 12
ur32207703 12
ur3892110 12
ur4491153 12
ur8554198 12
ur23756473 12
ur3741901 12
ur79972010 12
ur1231696 12
ur2533227 12
ur65813142 12
ur23883771 12
ur43903214 12
ur71543356 12
ur111777955 12
ur86636713 11
ur122069384 11
ur110613987 11
ur110600019 11
ur86309294 11
ur28354196 11
ur71182120 11
ur109104130 11
ur123796475 11
ur26401041 11
ur62702709 11
ur117143265 11
ur82450930 11
ur82438476 11
ur108788984 11
ur10879013 11
ur35965350 11
ur5358902 11
ur134361154 11
ur20199457 11
ur110309935 11
ur28757040 11
ur23415028 11
ur1506029 11
ur2608802 11
ur17807938 11
ur100201738 11
ur0103511 11
ur34893557 11
ur28683625 11
ur101128147 11
ur22518687 11
ur3922673 11
ur56071541 11
ur68448029 11
ur123203865 11
ur111086750 11
ur117862781 11
ur51204762 11
ur28459710 11
ur17658515 11
ur5368428 11
ur90868255 11
ur26779379 11
ur81440437 11
ur61462616 11
ur16178412 11
ur63848504 11
ur112790378 11
ur80507339 11
ur97849810 11
ur105187335 11
ur106582401 11
ur64557457 11
ur3805352 11
ur23749646 11
ur0179443 11
ur6997732 11
ur49666383 11
ur49237919 11
ur10986404 11
ur38555755 11
ur1678308 11
ur81477436 11
ur80180894 11
ur33809901 11
ur130605646 11
ur66204782 11
ur1657894 11
ur1640094 11
ur90455008 11
ur92949844 11
ur58740256 11
ur50619674 11
ur10840477 11
ur3286061 11
ur37259988 11
ur66046726 11
ur104138873 11
ur54800458 11
ur40191153 11
ur78766088 11
ur103998856 11
ur58137713 11
ur34835271 11
ur94682785 11
ur26432148 11
ur0749363 11
ur18941631 11
ur107395797 11
ur127152283 11
ur3310177 11
ur63109475 11
ur3032357 11
ur51703447 11
ur15780544 11
ur1147015 11
ur4217184 11
ur9139154 11
ur141878719 11
ur141941218 11
ur29911262 11
ur131861662 11
ur27953094 11
ur96996693 11
ur131742669 11
ur83633806 11
ur104701114 11
ur6150112 11
ur5267317 11
ur130361882 11
ur3257585 10
ur3361091 10
ur72472558 10
ur66832789 10
ur47115801 10
ur37874877 10
ur109116732 10
ur2130273 10
ur85426954 10
ur60305531 10
ur113638405 10
ur0909646 10
ur23391960 10
ur60255714 10
ur54063771 10
ur107995685 10
ur6958054 10
ur128745919 10
ur16833436 10
ur19721285 10
ur135543109 10
ur37327729 10
ur58787466 10
ur22563365 10
ur125506304 10
ur0426613 10
ur6568329 10
ur93820964 10
ur131898880 10
ur87061016 10
ur135925400 10
ur2568038 10
ur19932818 10
ur4234648 10
ur0412563 10
ur114304976 10
ur114361768 10
ur4997726 10
ur116125404 10
ur2094131 10
ur52382844 10
ur15339371 10
ur83340910 10
ur5232598 10
ur97064467 10
ur38356873 10
ur34934911 10
ur26911472 10
ur9480570 10
ur6501873 10
ur13074316 10
ur10958226 10
ur112234773 10
ur8248521 10
ur54207336 10
ur80802455 10
ur62277236 10
ur11127331 10
ur65900546 10
ur59148101 10
ur47918423 10
ur123793059 10
ur56258187 10
ur34087008 10
ur1937893 10
ur74656473 10
ur13178622 10
ur74704346 10
ur37377212 10
ur3289328 10
ur86626671 10
ur119836880 10
ur4413144 10
ur3436679 10
ur110262632 10
ur36494160 10
ur108708694 10
ur103624867 10
ur3167531 10
ur49208568 10
ur75904101 10
ur81971791 10
ur68166646 10
ur55532299 10
ur54148523 10
ur16657919 10
ur46993949 10
ur2510120 10
ur22113547 10
ur0139258 10
ur4374846 10
ur50947585 10
ur53150945 10
ur135746614 10
ur106304440 10
ur1622306 10
ur53568182 10
ur18271419 10
ur3260904 10
ur117501204 10
ur7868777 10
ur1285952 10
ur33283012 10
ur64317889 10
ur54588500 10
ur17899649 10
ur98946302 10
ur4640865 10
ur97769747 10
ur0002746 10
ur90270268 10
ur13691013 10
ur108950002 9
ur87749915 9
ur19532258 9
ur62119843 9

In [10]:
eliminated_user_ids = user_ids[user_id_idxes[:-1415]]

In [11]:
eliminated_user_ids

array(['ur0000011', 'ur3958569', 'ur39586391', ..., 'ur42744479',
       'ur71097662', 'ur9344916'], dtype='<U11')

In [12]:
eliminated_user_ids_df = pd.DataFrame(columns=['user id'])
eliminated_user_ids_df['user id'] = eliminated_user_ids

In [13]:
eliminated_user_ids_df.head()

      user id
0   ur0000011
1   ur3958569
2  ur39586391
3   ur3958905
4  ur39593965

In [14]:
eliminated_ratings_df = pd.merge(ratings, eliminated_user_ids_df, how='inner', left_on='user id', right_on='user id')
eliminated_ratings_df

,user id,movie id,rating,content,date
0,ur106993889,tt0102813,4,I remember renting this on VHS at a local gas ...,17 November 2019
1,ur106993889,tt9288776,5,China had 2 animated Blockbusters this year an...,26 December 2019
2,ur106993889,tt1107365,4,"Good animation at times, but looks like someth...",7 September 2019
3,ur106993889,tt0106140,5,Last decade nostalgia fans smashed the interne...,30 March 2020
4,ur106993889,tt0142074,4,To be based on real events about alien abducti...,29 March 2020
...,...,...,...,...,...
34128,ur86632441,tt10642154,5,I loved it! I've watched it alot! Love Melissa...,19 November 2020
34129,ur33402437,tt10642154,4,If you watch a Lifetime or Hallmark Christmas ...,10 November 2019
34130,ur73282794,tt10642154,4,"While not an award winner, this was pretty enj...",10 November 2019
34131,ur124415538,tt10642154,5,I enjoyed the movie due to the wonderful stars...,19 September 2020
34132,ur8379971,tt10642154,1,"Oversentimental, maudlin, cloying, sickly, sac...",22 November 2019

In [15]:
eliminated_ratings_df.to_csv('./data/datasets/rating/eliminated_detail.csv', sep=',', encoding='latin-1', index=False)

In [16]:
no_ratings_per_user

array([ 1,  2, 10, ...,  2,  1,  1], dtype=int64)

In [17]:
remaining_user_ids = user_ids[user_id_idxes[-1415:]]
print(len(remaining_user_ids))
remaining_user_ids

1415

array(['ur62119843', 'ur19532258', 'ur87749915', ..., 'ur5876717',
       'ur4248714', 'ur2898520'], dtype='<U11')

In [18]:
remaining_user_ids_df = pd.DataFrame(columns=['user id', 'user index'])
remaining_user_ids_df['user id'] = remaining_user_ids
remaining_user_ids_df['user index'] = range(len(remaining_user_ids))

In [19]:
remaining_user_ids_df.head()

       user id  user index
0   ur62119843           0
1   ur19532258           1
2   ur87749915           2
3  ur108950002           3
4   ur13691013           4

In [20]:
remaining_ratings_df = pd.merge(ratings, remaining_user_ids_df, how='inner', left_on='user id', right_on='user id')
remaining_ratings_df

,user id,movie id,rating,content,date,user index
0,ur20552756,tt0102813,3,I am a big fan of animated movies and of anima...,22 June 2011,1410
1,ur20552756,tt0075686,5,"Not everybody will love Woody Allen's humour, ...",9 February 2014,1410
2,ur20552756,tt0207120,2,"I like Spider-Man a great deal, I do like the ...",23 September 2012,1410
3,ur20552756,tt1402488,2,I want to start off saying that I liked the fi...,10 March 2012,1410
4,ur20552756,tt0857277,4,"Just last night, I was replying to a thread on...",8 August 2010,1410
...,...,...,...,...,...,...
127939,ur23466126,tt3596174,1,I happened to watch a few episodes a couple of...,20 October 2021,318
127940,ur23466126,tt6807662,3,Um ... I have to admit it's interesting. The s...,11 November 2020,318
127941,ur23466126,tt4145054,2,"So the first scenes are full of popped lips, p...",11 December 2020,318
127942,ur23466126,tt8103070,2,When I watch this series I have the feeling th...,5 August 2020,318
127943,ur23466126,tt1429449,2,I don't know if I would categorize this as a t...,31 August 2020,318

In [21]:
remaining_ratings_df['movie id'].unique()

array(['tt0102813', 'tt0075686', 'tt0207120', ..., 'tt9721776',
       'tt4648640', 'tt8045690'], dtype=object)

In [22]:
len(remaining_ratings_df['movie id'].unique())

9385

In [23]:
movie_ids = remaining_ratings_df['movie id'].value_counts().index.tolist()

In [24]:
movie_ids

['tt8510350',
 'tt3289956',
 'tt0097179',
 'tt5220122',
 'tt1525366',
 'tt4733640',
 'tt9182964',
 'tt3139086',
 'tt10168312',
 'tt11337862',
 'tt1278340',
 'tt6402468',
 'tt4281724',
 'tt0963794',
 'tt6556890',
 'tt8201186',
 'tt0048605',
 'tt0102768',
 'tt0088933',
 'tt0808279',
 'tt11686490',
 'tt8923854',
 'tt0095776',
 'tt0804516',
 'tt0048960',
 'tt6905686',
 'tt8332438',
 'tt7049682',
 'tt0080365',
 'tt0046183',
 'tt7658402',
 'tt6259380',
 'tt10736580',
 'tt0093437',
 'tt8663516',
 'tt0834001',
 'tt0059113',
 'tt7875794',
 'tt0385002',
 'tt0103786',
 'tt7949218',
 'tt9013182',
 'tt10048342',
 'tt1837492',
 'tt10062292',
 'tt7608028',
 'tt1817771',
 'tt5748448',
 'tt0075925',
 'tt5296406',
 'tt2296777',
 'tt0492044',
 'tt0049314',
 'tt0064349',
 'tt0052948',
 'tt8416494',
 'tt0118928',
 'tt0062994',
 'tt6156584',
 'tt1043813',
 'tt7991608',
 'tt1724970',
 'tt5774002',
 'tt2274648',
 'tt9359220',
 'tt1494772',
 'tt10262380',
 'tt8425404',
 'tt7073710',
 'tt2193021',
 'tt3717252',
 'tt1206885',
 'tt2249364',
 'tt4761916',
 'tt5689068',
 'tt0114194',
 'tt10620868',
 'tt7488208',
 'tt10752004',
 'tt10418662',
 'tt1073105',
 'tt11260832',
 'tt6218010',
 'tt8328716',
 'tt9772374',
 'tt7212754',
 'tt6269368',
 'tt10515988',
 'tt0057193',
 'tt5114356',
 'tt5580540',
 'tt4474344',
 'tt10763820',
 'tt0086491',
 'tt6048596',
 'tt1648179',
 'tt1869454',
 'tt1712170',
 'tt11027830',
 'tt0087075',
 'tt9140560',
 'tt0386676',
 'tt9140554',
 'tt8085790',
 'tt0096463',
 'tt11846996',
 'tt9110170',
 'tt1139668',
 'tt0082334',
 'tt0111280',
 'tt0091877',
 'tt5574490',
 'tt4348012',
 'tt4578118',
 'tt0062803',
 'tt0384793',
 'tt5348176',
 'tt4217392',
 'tt11125620',
 'tt2452242',
 'tt1183732',
 'tt3921180',
 'tt0389722',
 'tt0088286',
 'tt5618256',
 'tt0129290',
 'tt0069113',
 'tt9179552',
 'tt1190634',
 'tt0049406',
 'tt4058836',
 'tt8421350',
 'tt1031280',
 'tt10888594',
 'tt10795658',
 'tt11881160',
 'tt0108037',
 'tt0454919',
 'tt0077975',
 'tt10986410',
 'tt9446688',
 'tt8760932',
 'tt0054428',
 'tt4954522',
 'tt11651796',
 'tt9544034',
 'tt10919420',
 'tt2177461',
 'tt7472896',
 'tt0384537',
 'tt12361178',
 'tt11576124',
 'tt1733785',
 'tt5628902',
 'tt8574252',
 'tt10793644',
 'tt0082242',
 'tt0111742',
 'tt10183816',
 'tt0119707',
 'tt1104835',
 'tt5607976',
 'tt0088814',
 'tt0077394',
 'tt9894470',
 'tt0070903',
 'tt6513656',
 'tt0048445',
 'tt0072869',
 'tt7908628',
 'tt2303687',
 'tt0077588',
 'tt8772296',
 'tt11394332',
 'tt0083630',
 'tt0460780',
 'tt0054167',
 'tt7902072',
 'tt5540054',
 'tt0065938',
 'tt0067525',
 'tt0104257',
 'tt2386404',
 'tt5638642',
 'tt0384286',
 'tt0117110',
 'tt0065988',
 'tt2828996',
 'tt7740510',
 'tt8134742',
 'tt1034385',
 'tt0087078',
 'tt0096251',
 'tt11252440',
 'tt9173418',
 'tt0093894',
 'tt7424200',
 'tt0297284',
 'tt6301452',
 'tt6473300',
 'tt0077889',
 'tt11777040',
 'tt2675914',
 'tt8322060',
 'tt10530176',
 'tt8758086',
 'tt11750282',
 'tt0069427',
 'tt4669296',
 'tt11284280',
 'tt0108147',
 'tt3286052',
 'tt11307814',
 'tt7978672',
 'tt13372794',
 'tt0060708',
 'tt0060782',
 'tt0369226',
 'tt6535880',
 'tt0039502',
 'tt0308152',
 'tt0118615',
 'tt3095734',
 'tt10696784',
 'tt6468322',
 'tt11815682',
 'tt4998350',
 'tt9698480',
 'tt0113409',
 'tt11946300',
 'tt1172994',
 'tt0339840',
 'tt0102744',
 'tt10207090',
 'tt8210856',
 'tt0089908',
 'tt8697870',
 'tt0106965',
 'tt1772250',
 'tt0059557',
 'tt3007572',
 'tt2531336',
 'tt8089592',
 'tt3118452',
 'tt0100486',
 'tt1564585',
 'tt8064302',
 'tt7569576',
 'tt0105265',
 'tt0058385',
 'tt0475944',
 'tt6610158',
 'tt0078504',
 'tt0105459',
 'tt0092494',
 'tt1196141',
 'tt8119752',
 'tt3472226',
 'tt2091935',
 'tt2071645',
 'tt4765284',
 'tt3107288',
 'tt1312171',
 'tt4508902',
 'tt4477976',
 'tt9683478',
 'tt0091251',
 'tt6741278',
 'tt10481868',
 'tt9820556',
 'tt0070948',
 'tt11794642',
 'tt6616260',
 'tt8385474',
 'tt1826940',
 'tt7660850',
 'tt0064100',
 'tt7043012',
 'tt13406094',
 'tt5290382',
 'tt4430212',
 'tt2788432',
 'tt5363918',
 'tt6338498',
 'tt3526078',
 'tt7134908',
 'tt5580146',
 'tt9055008',
 'tt7493974',
 'tt9264728',
 'tt0076723',
 'tt0098621',
 'tt2702724',
 'tt0060728',
 'tt0348333',
 'tt9642938',
 'tt2403776',
 'tt0093693',
 'tt2023690',
 'tt0090329',
 'tt1077258',
 'tt2741602',
 'tt0489974',
 'tt4179452',
 'tt6866266',
 'tt1823672',
 'tt9052870',
 'tt1620981',
 'tt3554046',
 'tt2861424',
 'tt0080025',
 'tt5664636',
 'tt8110640',
 'tt0107206',
 'tt0093148',
 'tt4463894',
 'tt3281796',
 'tt7914416',
 'tt0058743',
 'tt0089880',
 'tt0067333',
 'tt0460627',
 'tt1220719',
 'tt9898858',
 'tt10834220',
 'tt9580138',
 'tt0093191',
 'tt0036641',
 'tt0114852',
 'tt0072856',
 'tt9100822',
 'tt0062883',
 'tt9831136',
 'tt0475784',
 'tt1714203',
 'tt7298596',
 'tt2234222',
 'tt7335184',
 'tt4052886',
 'tt8110330',
 'tt3322314',
 'tt0101393',
 'tt0057129',
 'tt9151230',
 'tt10350922',
 'tt6802400',
 'tt3358020',
 'tt0058529',
 'tt1526318',
 'tt7909970',
 'tt2250192',
 'tt0120770',
 'tt0802948',
 'tt8295472',
 'tt3322312',
 'tt11126994',
 'tt0074812',
 'tt4236770',
 'tt3749900',
 'tt9208876',
 'tt0096256',
 'tt0119396',
 'tt5675620',
 'tt2357547',
 'tt9251798',
 'tt0082431',
 'tt11762434',
 'tt2850386',
 'tt4698684',
 'tt2364582',
 'tt4955642',
 'tt0098253',
 'tt8721424',
 'tt0229440',
 'tt1129442',
 'tt0102975',
 'tt0354623',
 'tt0059243',
 'tt0046414',
 'tt0061619',
 'tt0103064',
 'tt0082288',
 'tt0084787',
 'tt0804555',
 'tt0253754',
 'tt0052561',
 'tt0103919',
 'tt0181739',
 'tt0051201',
 'tt0058536',
 'tt0054953',
 'tt0085936',
 'tt0032455',
 'tt0087544',
 'tt0099653',
 'tt0367594',
 'tt0082406',
 'tt0890870',
 'tt0464154',
 'tt0056687',
 'tt2403029',
 'tt0083972',
 'tt9426210',
 'tt0022835',
 'tt10293938',
 'tt2313197',
 'tt0790604',
 'tt0098554',
 'tt0115624',
 'tt1615918',
 'tt0103956',
 'tt1865505',
 'tt0080360',
 'tt0111070',
 'tt0452598',
 'tt0096446',
 'tt5690360',
 'tt0021814',
 'tt0071877',
 'tt0460649',
 'tt0107387',
 'tt0089686',
 'tt0071853',
 'tt0095953',
 'tt0111301',
 'tt0424205',
 'tt0479997',
 'tt0075005',
 'tt0089173',
 'tt0974583',
 'tt0082031',
 'tt11214590',
 'tt0105477',
 'tt4976512',
 'tt0443706',
 'tt1530509',
 'tt0023940',
 'tt0086006',
 'tt0050280',
 'tt0103639',
 'tt0065054',
 'tt0065214',
 'tt3371366',
 'tt2160105',
 'tt0039628',
 'tt0083530',
 'tt0058092',
 'tt0091129',
 'tt1474684',
 'tt0064418',
 'tt8031422',
 'tt0072732',
 'tt0078869',
 'tt1628841',
 'tt0107120',
 'tt0112625',
 'tt0088247',
 'tt0203425',
 'tt6298780',
 'tt0055830',
 'tt2709692',
 'tt1233227',
 'tt0808510',
 'tt0097388',
 'tt0033563',
 'tt0056575',
 'tt0120623',
 'tt0115685',
 'tt0091203',
 'tt0285531',
 'tt0095294',
 'tt4913966',
 'tt1025100',
 'tt0373883',
 'tt0098966',
 'tt0057413',
 'tt0097428',
 'tt1241317',
 'tt0082495',
 'tt0095271',
 'tt0388419',
 'tt1477076',
 'tt0089907',
 'tt0037514',
 'tt0084827',
 'tt0117731',
 'tt2398241',
 'tt7671598',
 'tt1311067',
 'tt2474976',
 'tt0095270',
 'tt5516328',
 'tt0410764',
 'tt1032815',
 'tt1187043',
 'tt6394324',
 'tt0089731',
 'tt11823076',
 'tt2279373',
 'tt0110366',
 'tt11083696',
 'tt0404390',
 'tt0264508',
 'tt2486678',
 'tt0408839',
 'tt2937366',
 'tt0419946',
 'tt2265171',
 'tt1212974',
 'tt0062407',
 'tt0113247',
 'tt1984153',
 'tt3949660',
 'tt1190536',
 'tt0286751',
 'tt1588170',
 'tt0332047',
 'tt0076162',
 'tt0092076',
 'tt1928330',
 'tt0091635',
 'tt0393685',
 'tt0056059',
 'tt12851524',
 'tt11804152',
 'tt6428676',
 'tt8954732',
 'tt0092718',
 'tt11199410',
 'tt4733624',
 'tt0455967',
 'tt5814534',
 'tt9866072',
 'tt5555260',
 'tt3152592',
 'tt0805647',
 'tt10121392',
 'tt9860728',
 'tt5562070',
 'tt9784456',
 'tt2974918',
 'tt4823776',
 'tt11681250',
 'tt4590256',
 'tt1893273',
 'tt5116302',
 'tt6587640',
 'tt7616798',
 'tt0104779',
 'tt0057007',
 'tt0054357',
 'tt1830713',
 'tt0068359',
 'tt5452780',
 'tt0076929',
 'tt0120844',
 'tt0044517',
 'tt1133985',
 'tt2231461',
 'tt0113253',
 'tt5742374',
 'tt0044706',
 'tt0489270',
 'tt0041594',
 'tt0091474',
 'tt0087985',
 'tt0070016',
 'tt0093177',
 'tt0112040',
 'tt0053291',
 'tt0073018',
 'tt0032904',
 'tt0060827',
 'tt0052357',
 'tt1475582',
 'tt0104348',
 'tt0419706',
 'tt0082198',
 'tt0424774',
 'tt1854564',
 'tt3829266',
 'tt0095489',
 'tt0063991',
 'tt0296042',
 'tt0088794',
 'tt0416496',
 'tt2118624',
 'tt0335438',
 'tt0387808',
 'tt0091149',
 'tt0098439',
 'tt2820466',
 'tt0102034',
 'tt0097474',
 'tt0107953',
 'tt0104409',
 'tt0120783',
 'tt0119310',
 'tt0070047',
 'tt3014284',
 'tt2177268',
 'tt0116514',
 'tt0105690',
 'tt0106220',
 'tt3440298',
 'tt0082418',
 'tt0061852',
 'tt0275947',
 'tt1137450',
 'tt0074119',
 'tt2870612',
 'tt0457433',
 'tt2002718',
 'tt0119395',
 'tt4136456',
 'tt0112950',
 'tt0095956',
 'tt10451914',
 'tt1571234',
 'tt1403241',
 'tt0901487',
 'tt3203528',
 'tt0372237',
 'tt0490076',
 'tt0092796',
 'tt10009030',
 'tt2382320',
 'tt0115571',
 'tt3889642',
 'tt1959332',
 'tt0905372',
 'tt6548228',
 'tt0449487',
 'tt10314450',
 'tt6654210',
 'tt1179034',
 'tt2908446',
 'tt0499097',
 'tt2592614',
 'tt0083624',
 'tt3428912',
 'tt5534434',
 'tt10682266',
 'tt2718440',
 'tt8299768',
 'tt3032476',
 'tt0118571',
 'tt1135985',
 'tt6932874',
 'tt0080749',
 'tt6433880',
 'tt6998518',
 'tt0800240',
 'tt1236246',
 'tt0088680',
 'tt0096945',
 'tt0082694',
 'tt0420294',
 'tt0113118',
 'tt9701940',
 'tt5734576',
 'tt10731768',
 'tt4266076',
 'tt7638348',
 'tt2737304',
 'tt2400463',
 'tt0282209',
 'tt6456326',
 'tt6475714',
 'tt4139588',
 'tt0468492',
 'tt0094761',
 'tt4225622',
 'tt0257076',
 'tt0118956',
 'tt2106651',
 'tt9288692',
 'tt6517102',
 'tt13024674',
 'tt8134186',
 'tt4986098',
 'tt2309021',
 'tt1255916',
 'tt9814116',
 'tt6794990',
 'tt2716382',
 'tt5774450',
 'tt7097896',
 'tt0271367',
 'tt7329656',
 'tt0085333',
 'tt10327354',
 'tt3850590',
 'tt6611916',
 'tt1686821',
 'tt0084516',
 'tt0063823',
 'tt1869716',
 'tt0338095',
 'tt6763664',
 'tt6086082',
 'tt8550800',
 'tt1853739',
 'tt0091306',
 'tt12838766',
 'tt8936646',
 'tt4520364',
 'tt11656892',
 'tt0092240',
 'tt8106534',
 'tt0074156',
 'tt9701942',
 'tt9387250',
 'tt0800069',
 'tt0068833',
 'tt11456054',
 'tt0104511',
 'tt4530884',
 'tt0101757',
 'tt0095583',
 'tt0085271',
 'tt2386237',
 'tt11024272',
 'tt10691162',
 'tt10962368',
 'tt8435002',
 'tt8461224',
 'tt7550000',
 'tt7026488',
 'tt1104836',
 'tt11079148',
 'tt10147644',
 'tt9398640',
 'tt5715066',
 'tt4513678',
 'tt7510346',
 'tt9794630',
 'tt9173154',
 'tt7985576',
 'tt2707408',
 'tt3230854',
 'tt9419056',
 'tt10228230',
 'tt0285728',
 'tt8745960',
 'tt7569592',
 'tt12298506',
 'tt11240506',
 'tt1918734',
 'tt3038708',
 'tt15198608',
 'tt7781432',
 'tt2027136',
 'tt12877640',
 'tt13651632',
 'tt5640450',
 'tt4181172',
 'tt2261227',
 'tt9812474',
 'tt1937149',
 'tt7058080',
 'tt5598292',
 'tt12971924',
 'tt13056008',
 'tt11390036',
 'tt11908982',
 'tt5085522',
 'tt11778118',
 'tt7917178',
 'tt6508228',
 'tt12383460',
 'tt5294518',
 'tt7057496',
 'tt9026184',
 'tt3658772',
 'tt4332232',
 'tt0152930',
 'tt8111088',
 'tt0089730',
 'tt0455760',
 'tt0112643',
 'tt0081793',
 'tt0077713',
 'tt0084777',
 'tt4805316',
 'tt0090094',
 'tt7979142',
 'tt4276618',
 'tt0089562',
 'tt11242218',
 'tt10327252',
 'tt1552211',
 'tt5071412',
 'tt4106514',
 'tt1020530',
 'tt6729080',
 'tt6214928',
 'tt2442560',
 'tt5973626',
 'tt9731534',
 'tt4192812',
 'tt0775440',
 'tt0096118',
 'tt0072354',
 'tt0455362',
 'tt0084472',
 'tt4685762',
 'tt0109635',
 'tt9032400',
 'tt0316732',
 'tt2452150',
 'tt9139220',
 'tt7016936',
 'tt1763264',
 'tt0101775',
 'tt7423538',
 'tt5865326',
 'tt8714904',
 'tt9059350',
 'tt5834204',
 'tt7937254',
 'tt8398600',
 'tt0081114',
 'tt1535616',
 'tt0080040',
 'tt0088117',
 'tt0082700',
 'tt3672742',
 'tt0094961',
 'tt0087957',
 'tt3626476',
 'tt0066518',
 'tt0120201',
 'tt0114558',
 'tt8001226',
 'tt0088961',
 'tt9844522',
 'tt5886046',
 'tt0120828',
 'tt8244784',
 'tt9314984',
 'tt0426459',
 'tt2938956',
 'tt0078767',
 'tt1800246',
 'tt0780622',
 'tt1082868',
 'tt0087597',
 'tt0075809',
 'tt1470023',
 'tt0080736',
 'tt9054904',
 'tt0096933',
 'tt0377062',
 'tt0111503',
 'tt0080377',
 'tt0105435',
 'tt3612126',
 'tt10970552',
 'tt3717490',
 'tt1288558',
 'tt5687612',
 'tt0462396',
 'tt2537176',
 'tt2473510',
 'tt3410834',
 'tt3420504',
 'tt6977338',
 'tt0773262',
 'tt0938330',
 'tt10155688',
 'tt5657846',
 'tt2784678',
 'tt0416315',
 'tt0077294',
 'tt1767382',
 'tt1634106',
 'tt0086320',
 'tt4016934',
 'tt0088024',
 'tt0081383',
 'tt0815245',
 'tt0089013',
 'tt0454082',
 'tt0099052',
 'tt0106697',
 'tt1408253',
 'tt0107798',
 'tt0060390',
 'tt9421570',
 'tt3011894',
 'tt0107076',
 'tt0862856',
 'tt0068421',
 'tt0079240',
 'tt0464141',
 'tt0089893',
 'tt0117500',
 'tt7120662',
 'tt10886166',
 'tt0432291',
 'tt0090859',
 'tt5171438',
 'tt1883367',
 'tt0079336',
 'tt0062873',
 'tt0074860',
 'tt0059646',
 'tt6571548',
 'tt2338151',
 'tt0113492',
 'tt7798634',
 'tt3794354',
 'tt4465572',
 'tt0077523',
 'tt1840309',
 'tt0111438',
 'tt0482606',
 'tt0094612',
 'tt0065225',
 'tt0082250',
 'tt0087050',
 'tt0093560',
 'tt0093407',
 'tt0102004',
 'tt0079117',
 'tt0068718',
 'tt0345950',
 'tt0089092',
 'tt0373074',
 'tt0068687',
 'tt0090837',
 'tt0073453',
 'tt0077269',
 'tt0100263',
 'tt0060980',
 'tt0108358',
 'tt0047034',
 'tt0079714',
 'tt6474378',
 'tt4396630',
 'tt10600398',
 'tt11525644',
 'tt4361050',
 'tt0071424',
 'tt0091630',
 'tt4532038',
 'tt0109402',
 'tt6257970',
 'tt0431021',
 'tt1091722',
 'tt0870154',
 'tt0293429',
 'tt7390588',
 'tt1500491',
 'tt2637294',
 'tt0410650',
 'tt10096842',
 'tt6560164',
 'tt4334266',
 'tt8058874',
 'tt0106856',
 'tt1709143',
 'tt4122068',
 'tt0093777',
 'tt1999995',
 'tt6378710',
 'tt0103893',
 'tt0100258',
 'tt7069210',
 'tt0089461',
 'tt0450314',
 'tt0059170',
 'tt0401855',
 'tt0498381',
 'tt6205872',
 'tt4255304',
 'tt0498353',
 'tt0071222',
 'tt1496025',
 'tt5113040',
 'tt1020885',
 'tt2679042',
 'tt5397194',
 'tt1220198',
 'tt14867006',
 'tt0066026',
 'tt10065694',
 'tt7153488',
 'tt10229558',
 'tt2980592',
 'tt1608290',
 'tt0119675',
 'tt0095963',
 'tt2473682',
 'tt0106673',
 'tt0364045',
 'tt2752772',
 'tt1855325',
 'tt2832470',
 ...]

In [25]:
len(movie_ids)

9385

In [26]:
movie_ids_df = pd.DataFrame(columns=['movie index', 'movie id'])
movie_ids_df['movie index'] = range(len(movie_ids))
movie_ids_df['movie id'] = movie_ids
movie_ids_df

      movie index    movie id
0               0   tt8510350
1               1   tt3289956
2               2   tt0097179
3               3   tt5220122
4               4   tt1525366
...           ...         ...
9380         9380   tt0201694
9381         9381  tt14035242
9382         9382  tt15316422
9383         9383  tt11834890
9384         9384   tt8045690

[9385 rows x 2 columns]

In [27]:
movie_ids_df[movie_ids_df['movie index'] == 9611]

Empty DataFrame
Columns: [movie index, movie id]
Index: []

In [28]:
merged_movie_ids_and_ratings = pd.merge(movie_ids_df, remaining_ratings_df, how='inner', left_on='movie id', right_on='movie id')
merged_movie_ids_and_ratings

,movie index,movie id,user id,rating,content,date,user index
0,0,tt8510350,ur5876717,4,"Not the running time in any sense, but this se...",31 October 2019,1412
1,0,tt8510350,ur22654354,2,I wasn't really sure what I was getting myself...,9 September 2019,1401
2,0,tt8510350,ur12844960,4,I didn't know what to expect of this flick bec...,2 May 2020,1347
3,0,tt8510350,ur0806494,4,2019 Oak Cliff Film Festival\nGreetings again ...,11 June 2019,1368
4,0,tt8510350,ur77881167,3,Sam (Hayley Griffith) delivers pizza and compo...,31 October 2019,1405
...,...,...,...,...,...,...,...
127939,9380,tt0201694,ur2444068,3,"Teenager Alex is shunned at school, a surprise...",3 May 2006,1292
127940,9381,tt14035242,ur122781086,3,"This film has a different format, it is a docu...",8 November 2021,584
127941,9382,tt15316422,ur54314810,3,Another story about a televised contest betwee...,30 November 2021,1297
127942,9383,tt11834890,ur79950921,1,If frankie came to hollywood...its a little bi...,24 November 2021,1331
127943,9384,tt8045690,ur59148101,3,Luis Miguel is arguably one of the most famous...,24 April 2018,56

In [29]:
merged_movie_ids_and_ratings[merged_movie_ids_and_ratings['movie id'] == 'tt3039472']

Empty DataFrame
Columns: [movie index, movie id, user id, rating, content, date, user index]
Index: []

In [30]:
merged_movie_ids_and_ratings['movie index'].unique()

array([   0,    1,    2, ..., 9382, 9383, 9384], dtype=int64)

In [31]:
movie_ids_df.head()

   movie index   movie id
0            0  tt8510350
1            1  tt3289956
2            2  tt0097179
3            3  tt5220122
4            4  tt1525366

In [32]:
merged_movie_ids_and_ratings.to_csv('./data/datasets/rating/remaining_detail.csv', sep=',', encoding='latin-1', index=False)